Repository mimblewimble/grin, pull requests merged in 2018-10, with the labels that each got.

#1630 Demo lean miner, minor PoW improvements
  core/src/global.rs
  core/src/pow/common.rs
  core/src/pow/cuckatoo.rs
  core/src/pow/cuckoo.rs
  core/src/pow/lean.rs
  core/src/pow/mod.rs
Labels: enhancement

#1644 Don't stall sync when header chain regresses
  servers/src/grin/sync.rs
Labels: bug

#1643 Don't push mined blocks to the chain during sync
  servers/src/mining/stratumserver.rs
Labels: bug

#1646 Resurrect a random peer on every monitor
  servers/src/grin/seed.rs
Labels: enhancement

#1660 Breaking down sync into multiple structs and files
  servers/src/grin/server.rs
  servers/src/grin/sync.rs
  servers/src/grin/sync/body_sync.rs
  servers/src/grin/sync/header_sync.rs
  servers/src/grin/sync/mod.rs
  servers/src/grin/sync/state_sync.rs
  servers/src/grin/sync/syncer.rs
Labels: enhancement

#1666 Reduce the scope of the chain new block lock
  chain/src/chain.rs
Labels: enhancement

#1673 Remove RwLock around individual peer instances
  api/src/handlers.rs
  p2p/src/handshake.rs
  p2p/src/peer.rs
  p2p/src/peers.rs
  p2p/src/serv.rs
  p2p/src/types.rs
  p2p/tests/peer_handshake.rs
  servers/src/common/adapters.rs
  servers/src/common/stats.rs
  servers/src/grin/seed.rs
  servers/src/grin/server.rs
  servers/src/grin/sync/body_sync.rs
  servers/src/grin/sync/header_sync.rs
  servers/src/grin/sync/state_sync.rs
  servers/src/grin/sync/syncer.rs
  servers/tests/api.rs
  servers/tests/simulnet.rs
  src/bin/cmd/client.rs
Labels: enhancement

#1696 a check of is_on_current_chain on body sync don't need a batch
  chain/src/chain.rs
  chain/src/store.rs
Labels: enhancement

#1699 fix: to avoid dead lock, always put txhashset.write before store.batch
  chain/src/chain.rs
Labels: bug

#1711 fix: panic at get_locator
  servers/src/grin/sync/header_sync.rs
Labels: bug

#1710 chain difficulty_iter don't need a WriteTransaction batch
  chain/src/chain.rs
  chain/src/pipe.rs
  chain/src/store.rs
Labels: enhancement

#1663 [T4 ONLY] T4 PoW changes
  chain/src/pipe.rs
  config/src/comments.rs
  core/src/genesis.rs
  core/src/global.rs
  core/src/pow/types.rs
  core/tests/block.rs
  servers/src/grin/server.rs
  servers/src/mining/stratumserver.rs
Labels: consensus breaking

#1719 small speed optimization for header sync
  p2p/src/protocol.rs
Labels: enhancement

#1729 feature: txhashset downloading progress display on tui
  p2p/src/conn.rs
  p2p/src/peer.rs
  p2p/src/peers.rs
  p2p/src/protocol.rs
  p2p/src/serv.rs
  p2p/src/types.rs
  servers/src/common/adapters.rs
  servers/src/common/types.rs
  servers/src/grin/sync/state_sync.rs
  src/bin/tui/status.rs
Labels: enhancement

#1723 [T4 ONLY] remove kernel sum header
  chain/src/pipe.rs
  core/tests/block.rs
  core/tests/core.rs
Labels: consensus breaking, enhancement, must-have

#1721 [T4] change compaction check trigger to 1 day and cut_through_horizon to 1 week
  core/src/consensus.rs
  core/src/global.rs
  servers/src/common/adapters.rs
Labels: consensus breaking, enhancement

#1709 [T4] Secondary proof of work difficulty adjustments
  chain/src/error.rs
  chain/src/pipe.rs
  chain/src/store.rs
  chain/tests/data_file_integrity.rs
  chain/tests/mine_simple_chain.rs
  chain/tests/test_coinbase_maturity.rs
  core/src/consensus.rs
  core/src/core/block.rs
  core/src/global.rs
  core/src/pow/lean.rs
  core/src/pow/types.rs
  core/tests/block.rs
  core/tests/consensus.rs
  core/tests/core.rs
  p2p/src/protocol.rs
  servers/src/common/types.rs
  servers/src/grin/server.rs
  servers/src/grin/sync/syncer.rs
  servers/src/mining/mine_block.rs
  wallet/tests/common/mod.rs
  wallet/tests/common/testclient.rs
Labels: enhancement

#1716 The Header MMR (One MMR To Rule Them All)
  api/src/types.rs
  chain/src/chain.rs
  chain/src/pipe.rs
  chain/src/txhashset/txhashset.rs
  chain/src/types.rs
  core/src/core/block.rs
  core/src/core/hash.rs
  core/src/core/pmmr/backend.rs
  core/src/core/pmmr/db_pmmr.rs
  core/src/core/pmmr/mod.rs
  core/src/core/pmmr/pmmr.rs
  core/src/core/pmmr/rewindable_pmmr.rs
  core/tests/pmmr.rs
  core/tests/vec_backend/mod.rs
  servers/src/grin/sync/header_sync.rs
  store/src/lib.rs
  store/src/pmmr.rs
  store/src/rm_log.rs
  store/src/types.rs
Labels: enhancement

#1746 kick stuck peer out of connected peers
  core/src/global.rs
  p2p/src/handshake.rs
  p2p/src/peer.rs
  p2p/src/peers.rs
  p2p/src/types.rs
Labels: enhancement

#1765 Secondary PoW scaling factor dampening, cleanup
  core/src/consensus.rs
  core/src/global.rs
  core/tests/consensus.rs
  servers/src/grin/server.rs
Labels: consensus breaking, enhancement

#1764 Commit to prev_root in block headers
  chain/src/chain.rs
  chain/src/pipe.rs
  chain/src/txhashset/txhashset.rs
  core/src/core/block.rs
  core/tests/block.rs
  servers/src/mining/mine_block.rs
Labels: consensus breaking, enhancement, must-have

#1793 replace stdlib RwLock and Mutex with parking_lot
  Cargo.lock
  api/src/handlers.rs
  chain/src/chain.rs
  chain/src/pipe.rs
  chain/src/store.rs
  chain/tests/data_file_integrity.rs
  chain/tests/mine_simple_chain.rs
  chain/tests/test_coinbase_maturity.rs
  core/src/core/block.rs
  core/src/core/committed.rs
  core/src/core/transaction.rs
  core/src/global.rs
  core/tests/block.rs
  core/tests/core.rs
  core/tests/verifier_cache.rs
  keychain/src/types.rs
  p2p/src/conn.rs
  p2p/src/handshake.rs
  p2p/src/peer.rs
  p2p/src/peers.rs
  p2p/src/types.rs
  pool/src/pool.rs
  pool/src/transaction_pool.rs
  pool/tests/block_building.rs
  pool/tests/block_reconciliation.rs
  pool/tests/coinbase_maturity.rs
  pool/tests/common/mod.rs
  pool/tests/transaction_pool.rs
  servers/src/common/adapters.rs
  servers/src/common/stats.rs
  servers/src/common/types.rs
  servers/src/grin/dandelion_monitor.rs
  servers/src/grin/server.rs
  servers/src/grin/sync/state_sync.rs
  servers/src/mining/mine_block.rs
  servers/src/mining/stratumserver.rs
  servers/src/mining/test_miner.rs
  servers/tests/api.rs
  servers/tests/dandelion.rs
  servers/tests/framework/mod.rs
  servers/tests/simulnet.rs
  servers/tests/wallet.rs
  src/bin/cmd/wallet.rs
  util/Cargo.toml
  util/src/lib.rs
  util/src/logger.rs
  util/src/secp_static.rs
  wallet/src/libtx/build.rs
  wallet/src/libtx/reward.rs
  wallet/src/libtx/slate.rs
  wallet/src/libwallet/api.rs
  wallet/src/libwallet/controller.rs
  wallet/src/libwallet/internal/tx.rs
  wallet/tests/accounts.rs
  wallet/tests/common/mod.rs
  wallet/tests/common/testclient.rs
  wallet/tests/restore.rs
Labels: enhancement

#1811 Cleanup sync loop
  servers/src/common/stats.rs
  servers/src/common/types.rs
  servers/src/grin/server.rs
  servers/src/grin/sync/header_sync.rs
  servers/src/grin/sync/syncer.rs
  src/bin/tui/status.rs
Labels: enhancement

#1844 Improve crate descriptors to be more cargo-friendly
  Cargo.lock
  Cargo.toml
  api/Cargo.toml
  chain/Cargo.toml
  config/Cargo.toml
  core/Cargo.toml
  keychain/Cargo.toml
  p2p/Cargo.toml
  pool/Cargo.toml
  servers/Cargo.toml
  src/bin/grin.rs
  src/bin/tui/version.rs
  src/build/build.rs
  store/Cargo.toml
  util/Cargo.toml
  wallet/Cargo.toml
Labels: enhancement

#1791 improve minimum difficulty handling
  api/src/types.rs
  chain/src/pipe.rs
  chain/src/store.rs
  chain/src/types.rs
  chain/tests/data_file_integrity.rs
  chain/tests/mine_simple_chain.rs
  chain/tests/store_indices.rs
  chain/tests/test_coinbase_maturity.rs
  core/fuzz/src/main.rs
  core/src/consensus.rs
  core/src/core/block.rs
  core/src/genesis.rs
  core/src/global.rs
  core/src/pow/mod.rs
  core/src/pow/types.rs
  core/tests/common/mod.rs
  core/tests/consensus.rs
  doc/api/node_api.md
  p2p/src/serv.rs
  p2p/tests/peer_handshake.rs
  pool/tests/block_building.rs
  pool/tests/block_reconciliation.rs
  pool/tests/transaction_pool.rs
  servers/src/mining/mine_block.rs
  wallet/tests/common/mod.rs
Labels: consensus breaking

#1882 adjust the title format of wallet txs output
  wallet/src/display.rs
Labels: enhancement
