Repository mimblewimble/grin, pull requests merged in 2018-05, with the labels that each got.

#1020 make kernel offsets commitments
  api/src/types.rs
  chain/src/txhashset.rs
  core/src/core/block.rs
  core/src/core/build.rs
  core/src/core/mod.rs
  core/src/core/transaction.rs
  core/src/ser.rs
  util/src/secp_static.rs
  wallet/src/receiver.rs
  wallet/src/sender.rs
  wallet/src/types.rs
Labels: consensus breaking

#1036 forgot to use the split key correctly
  wallet/src/sender.rs
Labels: bug, consensus breaking

#1050 Buffers writes in the MMR store types
  store/src/types.rs
Labels: enhancement

#1015 Improved (more compact) Merkle Proofs
  api/src/handlers.rs
  api/src/types.rs
  chain/src/chain.rs
  chain/src/txhashset.rs
  chain/src/types.rs
  chain/tests/test_coinbase_maturity.rs
  core/src/core/block.rs
  core/src/core/merkle_proof.rs
  core/src/core/mod.rs
  core/src/core/pmmr.rs
  core/src/core/transaction.rs
  core/tests/block.rs
  core/tests/core.rs
  core/tests/merkle_proof.rs
  core/tests/pmmr.rs
  core/tests/vec_backend/mod.rs
  pool/src/blockchain.rs
  pool/src/pool.rs
  pool/src/types.rs
  pool/tests/pool.rs
  servers/src/common/adapters.rs
  wallet/src/libwallet/build.rs
  wallet/src/types.rs
Labels: consensus breaking, enhancement

#1071 Remove redundant hashing of header before proof of work
  chain/src/chain.rs
  core/src/pow/cuckoo.rs
  core/src/pow/mod.rs
  doc/build.md
  doc/dandelion/images/Dandelion.xml
  doc/dandelion/images/t0.png
  doc/dandelion/images/t10.png
  doc/dandelion/images/t100.png
  doc/dandelion/images/t30.png
  doc/dandelion/images/t35.png
  doc/dandelion/images/t40.png
  doc/dandelion/images/t5.png
  doc/dandelion/images/t50.png
  doc/dandelion/images/t55.png
  doc/dandelion/images/t60.png
  doc/dandelion/images/t65.png
  doc/dandelion/images/t70.png
  doc/dandelion/images/t75.png
  doc/dandelion/images/t80.png
  doc/dandelion/images/t85.png
  doc/dandelion/images/t95_1.png
  doc/dandelion/images/t95_2.png
  doc/dandelion/images/t_i.png
  doc/dandelion/images/ti.png
  doc/dandelion/simulation.md
  servers/src/common/adapters.rs
  servers/src/grin/server.rs
  servers/src/mining/test_miner.rs
  src/bin/grin.rs
  store/src/types.rs
Labels: consensus breaking

#1073 Get block bodies from other fast sync'd nodes
  servers/src/grin/sync.rs
Labels: enhancement
