Repository mimblewimble/grin, pull requests merged in 2018-11, with the labels that each got.

#1836 validate root of header MMR when processing headers (during sync and full blocks)
  api/src/handlers.rs
  api/src/types.rs
  chain/src/chain.rs
  chain/src/pipe.rs
  chain/src/store.rs
  chain/src/txhashset/txhashset.rs
  chain/src/types.rs
  chain/tests/data_file_integrity.rs
  chain/tests/mine_simple_chain.rs
  chain/tests/store_indices.rs
  chain/tests/test_coinbase_maturity.rs
  chain/tests/test_txhashset.rs
  core/src/core/block.rs
  core/src/core/pmmr/db_pmmr.rs
  core/src/core/pmmr/pmmr.rs
  core/src/genesis.rs
  pool/tests/block_building.rs
  pool/tests/block_reconciliation.rs
  pool/tests/common/mod.rs
  servers/src/common/adapters.rs
  servers/src/grin/sync/body_sync.rs
  servers/src/grin/sync/header_sync.rs
  servers/src/grin/sync/state_sync.rs
  servers/src/mining/mine_block.rs
  servers/src/mining/test_miner.rs
  wallet/tests/common/mod.rs
Labels: enhancement

#1912 fix: more readable timestamp format for logging
  util/src/logger.rs
Labels: enhancement

#1923 protection of parallel requests of TxHashSetRequest
  chain/src/chain.rs
  chain/src/txhashset/txhashset.rs
  chain/tests/test_txhashset.rs
Labels: bug

#1953 Peer send receive bytes statistics missed response messages and attachment
  p2p/src/conn.rs
  p2p/src/protocol.rs
  src/bin/tui/peers.rs
Labels: enhancement

#1502 BIP39 Support
  Cargo.lock
  keychain/Cargo.toml
  keychain/src/extkey_bip32.rs
  keychain/src/keychain.rs
  keychain/src/lib.rs
  keychain/src/mnemonic.rs
  keychain/src/wordlists/en.txt
Labels: enhancement

#2037 Two year secondary pow ratio fix
  core/src/consensus.rs
  core/src/global.rs
  core/tests/consensus.rs
Labels: consensus breaking

#2042 Quick fix for graph_weight used with AR PoW
  core/src/consensus.rs
Labels: bug
