Repository mimblewimble/grin, pull requests merged in 2018-06, with the labels that each got.

#1147 Replace rm_log with leaf_set (compact bitmap)
  Cargo.lock
  chain/Cargo.toml
  chain/src/chain.rs
  chain/src/lib.rs
  chain/src/pipe.rs
  chain/src/store.rs
  chain/src/txhashset.rs
  chain/src/types.rs
  chain/tests/test_txhashset_raw_txs.rs
  core/Cargo.toml
  core/src/core/mod.rs
  core/src/core/pmmr.rs
  core/src/core/prune_list.rs
  core/src/lib.rs
  core/tests/pmmr.rs
  pool/tests/block_reconciliation.rs
  pool/tests/common/mod.rs
  store/Cargo.toml
  store/src/leaf_set.rs
  store/src/lib.rs
  store/src/pmmr.rs
  store/src/rm_log.rs
  store/src/types.rs
  store/tests/pmmr.rs
  store/tests/rm_log_perf.rs
  store/tests/test_bitmap.rs
  store/tests/utxo_set_perf.rs
  util/src/secp_static.rs
Labels: enhancement

#1119 [consensus breaking] New Improved Merkle Proofs
  api/src/types.rs
  chain/src/chain.rs
  chain/src/txhashset.rs
  chain/src/types.rs
  chain/tests/test_coinbase_maturity.rs
  chain/tests/test_txhashset_raw_txs.rs
  config/src/types.rs
  core/src/core/block.rs
  core/src/core/merkle_proof.rs
  core/src/core/mod.rs
  core/src/core/pmmr.rs
  core/src/core/transaction.rs
  core/tests/common/mod.rs
  core/tests/merkle_proof.rs
  core/tests/pmmr.rs
  core/tests/vec_backend/mod.rs
  keychain/src/extkey.rs
  keychain/src/types.rs
  pool/tests/common/mod.rs
  servers/src/mining/stratumserver.rs
  store/src/leaf_set.rs
  wallet/src/libtx/build.rs
  wallet/src/libwallet/types.rs
Labels: consensus breaking, enhancement

#1114 [consensus breaking] use hash_with_index(pos - 1) when checking the hash in the MMR
  chain/src/txhashset.rs
  pool/tests/block_reconciliation.rs
Labels: bug, consensus breaking

#1163 Kernel sum and MMR sizes in block header
  api/src/rest.rs
  chain/src/chain.rs
  chain/src/lib.rs
  chain/src/pipe.rs
  chain/src/store.rs
  chain/src/txhashset.rs
  chain/src/types.rs
  chain/tests/data_file_integrity.rs
  chain/tests/mine_simple_chain.rs
  chain/tests/test_coinbase_maturity.rs
  chain/tests/test_txhashset_raw_txs.rs
  core/src/core/block.rs
  core/src/core/committed.rs
  core/src/core/id.rs
  core/src/core/pmmr.rs
  core/src/core/transaction.rs
  core/src/ser.rs
  core/tests/block.rs
  core/tests/common/mod.rs
  core/tests/consensus.rs
  core/tests/core.rs
  core/tests/vec_backend/mod.rs
  keychain/src/extkey.rs
  keychain/src/types.rs
  p2p/src/handshake.rs
  p2p/src/msg.rs
  p2p/tests/peer_handshake.rs
  pool/tests/coinbase_maturity.rs
  pool/tests/common/mod.rs
  servers/src/common/adapters.rs
  servers/src/grin/sync.rs
  servers/src/mining/mine_block.rs
  src/bin/tui/menu.rs
  src/bin/tui/mining.rs
  src/bin/tui/peers.rs
  src/bin/tui/status.rs
  src/bin/tui/table.rs
  src/bin/tui/types.rs
  src/bin/tui/ui.rs
  src/bin/tui/version.rs
  store/src/leaf_set.rs
  store/src/pmmr.rs
  store/src/types.rs
  wallet/src/display.rs
  wallet/src/file_wallet.rs
  wallet/src/libtx/slate.rs
  wallet/src/libwallet/api.rs
  wallet/src/libwallet/error.rs
  wallet/src/libwallet/internal/selection.rs
  wallet/src/libwallet/internal/updater.rs
  wallet/tests/common/mod.rs
  wallet/tests/transaction.rs
Labels: consensus breaking

#1151 Wallet LMDB backend
  Cargo.lock
  api/src/handlers.rs
  chain/Cargo.toml
  chain/src/chain.rs
  chain/src/lib.rs
  chain/src/pipe.rs
  chain/src/store.rs
  chain/src/txhashset.rs
  chain/src/types.rs
  chain/tests/data_file_integrity.rs
  chain/tests/mine_simple_chain.rs
  chain/tests/store_indices.rs
  chain/tests/test_coinbase_maturity.rs
  chain/tests/test_txhashset_raw_txs.rs
  core/src/core/block.rs
  core/src/core/committed.rs
  p2p/Cargo.toml
  p2p/src/lib.rs
  p2p/src/serv.rs
  p2p/src/store.rs
  p2p/tests/peer_handshake.rs
  pool/Cargo.toml
  pool/tests/block_building.rs
  pool/tests/block_reconciliation.rs
  pool/tests/common/mod.rs
  pool/tests/transaction_pool.rs
  servers/Cargo.toml
  servers/src/grin/server.rs
  servers/src/lib.rs
  src/bin/grin.rs
  store/Cargo.toml
  store/src/lib.rs
  store/src/lmdb.rs
  util/src/logger.rs
  wallet/Cargo.toml
  wallet/src/file_wallet.rs
  wallet/src/lib.rs
  wallet/src/libwallet/error.rs
  wallet/src/libwallet/internal/keys.rs
  wallet/src/libwallet/internal/restore.rs
  wallet/src/libwallet/internal/selection.rs
  wallet/src/libwallet/internal/tx.rs
  wallet/src/libwallet/internal/updater.rs
  wallet/src/libwallet/types.rs
  wallet/src/lmdb_wallet.rs
  wallet/src/types.rs
  wallet/tests/transaction.rs
Labels: consensus breaking

#1116 Less truncation in difficulty calculation
  core/src/consensus.rs
Labels: consensus breaking

#1118 Remove redundant hashing of header before proof of work
  core/src/pow/cuckoo.rs
  core/src/pow/mod.rs
  servers/src/mining/test_miner.rs
Labels: consensus breaking

#1193 Accept multiple Cuckoo graph sizes
  chain/src/pipe.rs
  chain/src/types.rs
  chain/tests/data_file_integrity.rs
  chain/tests/mine_simple_chain.rs
  chain/tests/test_coinbase_maturity.rs
  core/src/consensus.rs
  core/src/core/mod.rs
  core/src/core/target.rs
  core/src/global.rs
  core/src/pow/cuckoo.rs
  core/src/pow/mod.rs
  core/tests/block.rs
  servers/src/grin/server.rs
  servers/src/mining/stratumserver.rs
  servers/src/mining/test_miner.rs
  src/bin/grin.rs
  wallet/src/display.rs
  wallet/src/file_wallet.rs
  wallet/src/libtx/build.rs
  wallet/src/libtx/reward.rs
  wallet/src/libwallet/api.rs
  wallet/src/libwallet/controller.rs
  wallet/src/libwallet/error.rs
  wallet/src/libwallet/internal/restore.rs
  wallet/src/libwallet/internal/selection.rs
  wallet/src/libwallet/internal/updater.rs
  wallet/src/lmdb_wallet.rs
  wallet/tests/common/mod.rs
Labels: consensus breaking
