Repository mimblewimble/grin, pull requests merged in 2019-04, with the labels that each got.

#2722 Return Result from methods of ChainAdapter
  Cargo.lock
  p2p/Cargo.toml
  p2p/src/lib.rs
  p2p/src/peer.rs
  p2p/src/peers.rs
  p2p/src/protocol.rs
  p2p/src/serv.rs
  p2p/src/store.rs
  p2p/src/types.rs
  servers/src/common/adapters.rs
  servers/src/grin/seed.rs
  servers/src/grin/sync/body_sync.rs
  servers/src/grin/sync/syncer.rs
Labels: task

#2738 pull initial chain compaction out of init() and into the syncer
  chain/src/chain.rs
  servers/src/grin/sync/syncer.rs
Labels: enhancement

#2734 [1.1.0] Support variable size PMMR (optional size_file)
  chain/src/txhashset/txhashset.rs
  core/src/core/block.rs
  core/src/core/pmmr/pmmr.rs
  core/src/ser.rs
  store/src/pmmr.rs
  store/src/prune_list.rs
  store/src/types.rs
  store/tests/pmmr.rs
Labels: enhancement

#2753 use a grin specific tmp dir instead of a system tmp dir
  chain/src/chain.rs
  p2p/src/peer.rs
  p2p/src/peers.rs
  p2p/src/protocol.rs
  p2p/src/serv.rs
  p2p/src/types.rs
  servers/src/common/adapters.rs
Labels: enhancement

#2773 Increasing thread sleeps for socket listener thread and per-connection threads
  p2p/src/conn.rs
  p2p/src/serv.rs
Labels: enhancement

#2775 Fix unused import warnings
  Cargo.lock
  core/src/core/pmmr/backend.rs
  core/src/core/pmmr/pmmr.rs
Labels: task

#2764 relax our p2p rules around matching protocol versions
  p2p/src/handshake.rs
  p2p/src/msg.rs
  p2p/src/types.rs
  servers/src/grin/server.rs
  src/bin/tui/ui.rs
Labels: bug

#2763 bump the version of croaring to 0.3.9
  Cargo.lock
  chain/Cargo.toml
  core/Cargo.toml
  store/Cargo.toml
Labels: task

#2757 cleanup how we deal with fixed size vs variable size data files
  store/src/pmmr.rs
  store/src/types.rs
Labels: enhancement

#2754 Increase peer max count significantly
  config/src/comments.rs
  p2p/src/types.rs
Labels: enhancement

#2780 Fix peer dropping
  p2p/src/conn.rs
  p2p/src/peer.rs
Labels: bug

#2758 bucket_transactions is now fee_to_weight aware
  core/src/core/transaction.rs
  pool/src/pool.rs
  pool/tests/block_building.rs
  pool/tests/block_max_weight.rs
Labels: enhancement

#2788 add debug logging on startup to provide size of our leaf_set (UTXO set)
  store/src/leaf_set.rs
  store/src/prune_list.rs
Labels: enhancement
