Repository mimblewimble/grin, pull requests merged in 2019-07, with the labels that each got.

#2876 Always stem local txs if configured that way (unless explicitly fluffed)
  api/src/handlers/pool_api.rs
  config/src/comments.rs
  pool/src/pool.rs
  pool/src/transaction_pool.rs
  pool/src/types.rs
  pool/tests/common.rs
  pool/tests/transaction_pool.rs
  servers/src/common/adapters.rs
  servers/src/common/types.rs
  servers/src/grin/dandelion_monitor.rs
Labels: enhancement

#2834 Check for known block when processing "header first"
  chain/src/pipe.rs
Labels: enhancement

#2856 [2.x.x] Writeable protocol version aware
  api/src/handlers/pool_api.rs
  api/src/types.rs
  chain/src/chain.rs
  core/src/core/block.rs
  core/src/core/hash.rs
  core/src/core/merkle_proof.rs
  core/src/core/transaction.rs
  core/src/genesis.rs
  core/src/global.rs
  core/src/ser.rs
  core/tests/block.rs
  core/tests/core.rs
  core/tests/merkle_proof.rs
  core/tests/transaction.rs
  p2p/src/conn.rs
  p2p/src/handshake.rs
  p2p/src/msg.rs
  p2p/src/peer.rs
  p2p/src/protocol.rs
  servers/src/grin/server.rs
  servers/src/mining/stratumserver.rs
  store/src/lmdb.rs
  store/src/pmmr.rs
  store/src/types.rs
Labels: enhancement

#2943 [2.x.x] Fix check_known logic for blocks/headers
  chain/src/chain.rs
  chain/src/pipe.rs
Labels: bug

#2945 perf: One less DB call when verifying block sums
  chain/src/pipe.rs
Labels: enhancement

#2908 [2.x.x] simplify txhashset zip creation and extraction
  Cargo.lock
  chain/src/txhashset/txhashset.rs
  chain/tests/test_txhashset.rs
  util/Cargo.toml
  util/src/file.rs
  util/src/zip.rs
  util/tests/file.rs
  util/tests/test.zip
  util/tests/zip.rs
Labels: enhancement

#2855 [2.x.x] Use blocking IO in P2P to reduce CPU load
  chain/src/chain.rs
  core/src/core/block.rs
  core/src/global.rs
  core/src/pow.rs
  core/src/pow/cuckarood.rs
  core/src/ser.rs
  p2p/src/conn.rs
  p2p/src/msg.rs
  store/src/types.rs
  util/src/lib.rs
  util/src/read_write.rs
Labels: enhancement

#2952 [DOC] Translate documents & fix some typo
  api/src/handlers/transactions_api.rs
  doc/coinbase_maturity.md
  doc/coinbase_maturity_KR.md
Labels: enhancement

#2951 [2.x.x] Generate txhashset archives on 720 block intervals.
  chain/src/chain.rs
  chain/src/txhashset/txhashset.rs
  chain/tests/chain_test_helper.rs
  chain/tests/test_txhashset_archive.rs
  core/src/global.rs
  core/src/pow.rs
  p2p/src/peer.rs
  p2p/src/peers.rs
  p2p/src/protocol.rs
  p2p/src/serv.rs
  p2p/src/types.rs
  servers/src/common/adapters.rs
  servers/src/grin/sync/state_sync.rs
Labels: enhancement

#2962 [2.x.x] Use a sensible txhashset interval for "user testing".
  core/src/global.rs
Labels: enhancement

#2963 [2.x.x] CI Improvements
  .ci/install.yml
  azure-pipelines.yml
Labels: enhancement

#2974 Merge master onto milestone/2.x.x
  Cargo.lock
  SECURITY.md
  core/src/consensus.rs
  doc/intro_SE.md
  p2p/src/conn.rs
  servers/src/grin/server.rs
  servers/src/grin/sync/body_sync.rs
  src/bin/grin.rs
  src/bin/grin.yml
Labels: task

#2918 Rewind head and header_head consistently.
  chain/src/chain.rs
  chain/src/pipe.rs
  chain/src/store.rs
  chain/src/txhashset/txhashset.rs
  chain/tests/chain_test_helper.rs
  chain/tests/data_file_integrity.rs
  chain/tests/mine_simple_chain.rs
  chain/tests/store_indices.rs
  chain/tests/test_txhashset_archive.rs
  pool/tests/common.rs
  store/src/types.rs
Labels: enhancement

#2976 Prune list robustness
  store/src/prune_list.rs
  store/tests/prune_list.rs
Labels: enhancement
