Repository mimblewimble/grin, pull requests merged in 2019-02, with the labels that each got.

#2487 Rework "bucket transactions" logic (buckets are now weight limited)
  core/src/core/transaction.rs
  core/src/global.rs
  core/tests/block.rs
  p2p/src/msg.rs
  pool/src/pool.rs
  pool/src/types.rs
  pool/tests/block_max_weight.rs
  src/bin/cmd/wallet_tests.rs
Labels: enhancement

#2511 bump for v1.0.1
  Cargo.lock
  Cargo.toml
  api/Cargo.toml
  chain/Cargo.toml
  config/Cargo.toml
  core/Cargo.toml
  keychain/Cargo.toml
  p2p/Cargo.toml
  pool/Cargo.toml
  servers/Cargo.toml
  src/bin/grin.yml
  store/Cargo.toml
  util/Cargo.toml
  wallet/Cargo.toml
Labels: task

#2506 Set max number of connections for peer db
  servers/src/grin/server.rs
  store/src/lmdb.rs
Labels: enhancement

#2491 Feature/slate version
  core/src/libtx/slate.rs
Labels: enhancement

#2517 fix wallet --data-dir flag
  src/bin/cmd/wallet_args.rs
Labels: bug

#2536 refactor: use less memory in verifier_cache by storing zero-sized type instead of bool
  core/src/core/verifier_cache.rs
Labels: enhancement

#2537 Allow to have more than min_peers/2 outbound peers
  p2p/src/peers.rs
  servers/src/grin/seed.rs
Labels: bug

#2539 fix: false positive wallet tests
  wallet/tests/restore.rs
  wallet/tests/transaction.rs
Labels: bug

#2547 Generate API secret in wallet --here mode
  config/src/config.rs
  src/bin/cmd/config.rs
Labels: bug

#2468 introduce an async version of stratum server.
  Cargo.lock
  servers/Cargo.toml
  servers/src/grin/server.rs
  servers/src/mining/stratumserver.rs
Labels: enhancement

#2535 Windows Compatibility Fixes #1
  Cargo.lock
  Cargo.toml
  chain/src/chain.rs
  chain/src/txhashset/txhashset.rs
  core/Cargo.toml
  core/src/core/pmmr/backend.rs
  core/tests/vec_backend.rs
  src/bin/cmd/server.rs
  src/bin/grin.yml
  store/Cargo.toml
  store/src/lmdb.rs
  store/src/pmmr.rs
  store/src/types.rs
  store/tests/pmmr.rs
  util/src/zip.rs
  wallet/src/test_framework/testclient.rs
  wallet/tests/restore.rs
Labels: enhancement

#2553 add repost method into wallet owner api
  doc/api/wallet_owner_api.md
  wallet/src/controller.rs
Labels: enhancement

#2516 Add ability to compare selection strategies
  src/bin/cmd/wallet_args.rs
  src/bin/grin.yml
  wallet/src/command.rs
  wallet/src/display.rs
  wallet/src/libwallet/api.rs
  wallet/src/libwallet/internal/selection.rs
  wallet/src/libwallet/internal/tx.rs
  wallet/tests/transaction.rs
Labels: enhancement

#2546 fix: wallet coin selection respects max_block_weight
  servers/tests/framework.rs
  servers/tests/simulnet.rs
  src/bin/cmd/wallet_args.rs
  wallet/src/command.rs
  wallet/src/controller.rs
  wallet/src/libwallet/api.rs
  wallet/src/libwallet/internal/selection.rs
  wallet/src/libwallet/internal/tx.rs
  wallet/src/libwallet/types.rs
  wallet/src/test_framework/mod.rs
  wallet/tests/accounts.rs
  wallet/tests/check.rs
  wallet/tests/file.rs
  wallet/tests/repost.rs
  wallet/tests/restore.rs
  wallet/tests/self_send.rs
  wallet/tests/transaction.rs
Labels: enhancement

#2528 Fix handling of IO WouldBlock error in Stratum server
  servers/src/mining/stratumserver.rs
Labels: bug

#2564 refactor/fix: use sort_unstable instead of sort, more efficient with_* methods for TransactionBody
  core/src/core/compact_block.rs
  core/src/core/transaction.rs
  core/src/pow/cuckatoo.rs
  core/src/pow/types.rs
Labels: enhancement

#2573 refactor: get rid of default implementation of Hashed trait for writable things
  chain/src/txhashset/utxo_view.rs
  chain/src/types.rs
  core/src/core/block.rs
  core/src/core/compact_block.rs
  core/src/core/hash.rs
  core/src/core/id.rs
  core/src/core/transaction.rs
  core/src/pow/types.rs
  core/src/ser.rs
  core/tests/vec_backend.rs
  servers/src/mining/stratumserver.rs
  store/tests/pmmr.rs
Labels: enhancement

#2575 clean-up the txhashset zip file and temp folder
  chain/src/chain.rs
  chain/src/txhashset/txhashset.rs
  chain/tests/test_txhashset.rs
Labels: enhancement

#2579 Fix compiler warnings
  config/src/config.rs
  src/bin/cmd/server.rs
Labels: task

#2556 fix deadlock between get_status and main loop
  servers/src/mining/stratumserver.rs
Labels: bug

#2540 Map peers by ip only (ignoring port unless on loopback ip)
  api/src/handlers/peers_api.rs
  p2p/fuzz/fuzz_targets/read_peer_addr.rs
  p2p/src/handshake.rs
  p2p/src/lib.rs
  p2p/src/msg.rs
  p2p/src/peer.rs
  p2p/src/peers.rs
  p2p/src/protocol.rs
  p2p/src/serv.rs
  p2p/src/store.rs
  p2p/src/types.rs
  p2p/tests/peer_handshake.rs
  servers/src/common/adapters.rs
  servers/src/grin/seed.rs
  servers/src/grin/server.rs
  servers/src/grin/sync/header_sync.rs
  servers/tests/framework.rs
  servers/tests/simulnet.rs
  src/bin/cmd/server.rs
Labels: enhancement

#2567 refactor: allocation free cut through algorithms
  core/src/core/transaction.rs
Labels: enhancement

#2602 debug how long it takes to verify the kernel sums for fast sync
  chain/src/txhashset/txhashset.rs
Labels: enhancement

#2600 chain_data/grin.lock to prevent multiple grin processes running from same dir
  Cargo.lock
  servers/Cargo.toml
  servers/src/common/types.rs
  servers/src/grin/server.rs
Labels: enhancement

#2621 Remove some unwrap/expect in chain crate
  chain/src/chain.rs
  chain/src/error.rs
  chain/src/txhashset/rewindable_kernel_view.rs
  chain/src/txhashset/txhashset.rs
  core/src/core/pmmr/rewindable_pmmr.rs
Labels: task

#2623 Bump version to 1.0.2
  Cargo.lock
  Cargo.toml
  api/Cargo.toml
  chain/Cargo.toml
  config/Cargo.toml
  core/Cargo.toml
  keychain/Cargo.toml
  p2p/Cargo.toml
  pool/Cargo.toml
  servers/Cargo.toml
  src/bin/grin.yml
  store/Cargo.toml
  util/Cargo.toml
  wallet/Cargo.toml
Labels: task

#2624 Don't extract unexpected files from txhashset archive
  Cargo.lock
  chain/Cargo.toml
  chain/src/txhashset/txhashset.rs
  chain/tests/test_txhashset.rs
  util/src/zip.rs
  util/tests/test.zip
  util/tests/zip.rs
Labels: enhancement

#2625 cleanup legacy "3 dot" incorrect filename check
  chain/src/txhashset/txhashset.rs
  store/src/pmmr.rs
Labels: task

#2543 Allow to peers behind NAT to get up to preferred_max connections
  servers/src/grin/seed.rs
Labels: enhancement

#2626 [1.1.0] Travis automated windows builds
  .auto-release.sh
  .travis.yml
Labels: enhancement

#2627 Reduce usage of unwrap in p2p crate
  p2p/src/conn.rs
  p2p/src/msg.rs
  p2p/src/peer.rs
  p2p/src/peers.rs
  p2p/src/protocol.rs
  p2p/src/store.rs
  p2p/src/types.rs
  store/src/lmdb.rs
Labels: task

#2605 Dynamic LMDB mapsize allocation [1.1.0]
  Cargo.lock
  chain/Cargo.toml
  chain/src/chain.rs
  chain/src/lib.rs
  chain/src/store.rs
  chain/tests/data_file_integrity.rs
  chain/tests/mine_simple_chain.rs
  chain/tests/store_indices.rs
  chain/tests/test_coinbase_maturity.rs
  chain/tests/test_txhashset.rs
  p2p/Cargo.toml
  p2p/src/lib.rs
  p2p/src/serv.rs
  p2p/src/store.rs
  p2p/tests/peer_handshake.rs
  pool/tests/common.rs
  servers/src/grin/server.rs
  servers/src/mining/stratumserver.rs
  store/src/lib.rs
  store/src/lmdb.rs
  store/tests/lmdb.rs
  util/src/lib.rs
  util/src/read_write.rs
Labels: enhancement

#2609 Simplify (and fix) output_pos cleanup during chain compaction
  chain/src/chain.rs
  chain/src/error.rs
  chain/src/store.rs
  chain/src/txhashset/txhashset.rs
  core/src/core/pmmr/backend.rs
  core/src/core/pmmr/pmmr.rs
  core/tests/vec_backend.rs
  p2p/src/store.rs
  store/src/leaf_set.rs
  store/src/lmdb.rs
  store/src/pmmr.rs
  store/src/types.rs
  store/tests/pmmr.rs
  wallet/src/lmdb_wallet.rs
Labels: bug
