Repository mimblewimble/grin, pull requests merged in 2019-09, with the labels that each got.

#2961 schnorr signature batch verification
  chain/src/txhashset/txhashset.rs
  core/src/core/transaction.rs
Labels: enhancement

#3017 use head (not header_head) when rewinding full blocks
  chain/src/chain.rs
  chain/src/pipe.rs
  chain/tests/mine_simple_chain.rs
Labels: bug, fixed

#3015 fix: the race condition in compact
  chain/src/chain.rs
  chain/src/txhashset/txhashset.rs
Labels: bug, fixed

#3004 Split header MMR (and sync MMR) out from txhashset
  chain/src/chain.rs
  chain/src/pipe.rs
  chain/src/txhashset/txhashset.rs
  chain/src/txhashset/utxo_view.rs
  chain/src/types.rs
  chain/tests/store_indices.rs
  chain/tests/test_txhashset.rs
  core/src/core/pmmr/pmmr.rs
  core/src/core/pmmr/readonly_pmmr.rs
  servers/src/common/adapters.rs
  servers/src/grin/server.rs
  src/bin/tui/ui.rs
Labels: enhancement

#3033 fix: find common header between the header chain and the current body chain
  chain/src/chain.rs
Labels: bug, fixed

#3029 fix: the cpuload 100% in case the tcpstream WouldBlock
  p2p/src/conn.rs
Labels: bug, fixed

#2966 Add sync_status in status Node API
  api/src/handlers.rs
  api/src/handlers/server_api.rs
  api/src/types.rs
  chain/src/types.rs
  servers/src/grin/server.rs
Labels: enhancement

#3034 Kernels v2 (variable size)
  api/src/handlers/pool_api.rs
  core/src/core/transaction.rs
  core/src/global.rs
  core/src/ser.rs
  core/tests/block.rs
  core/tests/core.rs
  core/tests/vec_backend.rs
  p2p/src/handshake.rs
Labels: enhancement

#3050 bump version for 2.1.0 dev (still on master)
  Cargo.lock
  Cargo.toml
  api/Cargo.toml
  chain/Cargo.toml
  config/Cargo.toml
  core/Cargo.toml
  keychain/Cargo.toml
  p2p/Cargo.toml
  pool/Cargo.toml
  servers/Cargo.toml
  store/Cargo.toml
  util/Cargo.toml
Labels: task

#3046 fix: Add some more stats to basic status page of TUI (disk usage, chain timestamp, tx pool size)
  Cargo.lock
  chain/src/chain.rs
  servers/Cargo.toml
  servers/src/common/stats.rs
  servers/src/grin/server.rs
  src/bin/tui/peers.rs
  src/bin/tui/status.rs
Labels: enhancement

#3051 support for v2 txhashset (continuing to use v1 in mainnet and floonet)
  chain/src/chain.rs
  chain/src/txhashset/txhashset.rs
  core/src/core/transaction.rs
  store/src/pmmr.rs
  store/src/types.rs
  store/tests/lmdb.rs
  store/tests/pmmr.rs
Labels: enhancement

#3054 Timeout Client requests after 20 seconds
  Cargo.lock
  api/Cargo.toml
  api/src/client.rs
Labels: enhancement

#3060 add block_hash to head_info so we can easily use them later
  chain/src/store.rs
  core/src/consensus.rs
  core/tests/consensus.rs
  servers/src/grin/server.rs
Labels: bug

#3059 Add missing doc and route for Node API
  api/src/handlers.rs
  doc/api/node_api.md
Labels: enhancement

#3062 Update zeroize to 0.9.3
  Cargo.lock
Labels: enhancement

#3066 bump version number v2.1.0-beta.2
  Cargo.lock
  Cargo.toml
  api/Cargo.toml
  chain/Cargo.toml
  config/Cargo.toml
  core/Cargo.toml
  keychain/Cargo.toml
  p2p/Cargo.toml
  pool/Cargo.toml
  servers/Cargo.toml
  store/Cargo.toml
  util/Cargo.toml
Labels: task
