Repository mimblewimble/grin, pull requests merged in 2019-11, with the labels that each got.

#3057 Refactor transaction building combinators
  chain/tests/mine_simple_chain.rs
  chain/tests/test_coinbase_maturity.rs
  core/src/core/transaction.rs
  core/src/libtx/build.rs
  core/src/libtx/error.rs
  core/tests/block.rs
  core/tests/common.rs
  core/tests/core.rs
  pool/tests/common.rs
Labels: P3: Fix if time, enhancement

#3064 feat: TUI logs view
  config/src/comments.rs
  config/src/config.rs
  config/src/types.rs
  servers/src/common.rs
  servers/src/grin/server.rs
  src/bin/cmd/server.rs
  src/bin/grin.rs
  src/bin/tui/constants.rs
  src/bin/tui/logs.rs
  src/bin/tui/menu.rs
  src/bin/tui/mod.rs
  src/bin/tui/ui.rs
  util/src/lib.rs
  util/src/logger.rs
  util/src/types.rs
Labels: P3: Fix if time, enhancement

#3110 Remove error serialization/deserialization
  core/src/core/committed.rs
  core/src/core/transaction.rs
  core/src/libtx/error.rs
  core/src/ser.rs
  keychain/src/extkey_bip32.rs
  keychain/src/mnemonic.rs
  keychain/src/types.rs
Labels: task

#3112 Make imports in core crate more Rust 2018 idiomatic
  core/Cargo.toml
  core/src/consensus.rs
  core/src/core.rs
  core/src/core/block.rs
  core/src/core/block_sums.rs
  core/src/core/committed.rs
  core/src/core/compact_block.rs
  core/src/core/hash.rs
  core/src/core/id.rs
  core/src/core/merkle_proof.rs
  core/src/core/transaction.rs
  core/src/core/verifier_cache.rs
  core/src/genesis.rs
  core/src/global.rs
  core/src/lib.rs
  core/src/libtx/aggsig.rs
  core/src/libtx/build.rs
  core/src/libtx/error.rs
  core/src/libtx/proof.rs
  core/src/libtx/reward.rs
  core/src/libtx/secp_ser.rs
  core/src/pow.rs
  core/src/pow/common.rs
  core/src/pow/cuckatoo.rs
  core/src/pow/types.rs
  core/src/ser.rs
  core/tests/block.rs
  core/tests/common.rs
  core/tests/core.rs
  core/tests/transaction.rs
  core/tests/verifier_cache.rs
  keychain/src/lib.rs
Labels: task

#3111 add tx pool kernel counts to tui status page
  pool/src/pool.rs
  servers/src/common/stats.rs
  servers/src/grin/server.rs
  src/bin/tui/status.rs
Labels: enhancement

#3121 Remove grin-tech from DNS seeds
  servers/src/grin/seed.rs
Labels: task

#3096 fix: split state validation status into kernel and rproof updates.
  api/src/handlers/server_api.rs
  chain/src/txhashset/txhashset.rs
  chain/src/types.rs
  core/src/core/pmmr/backend.rs
  core/src/core/pmmr/pmmr.rs
  core/tests/vec_backend.rs
  servers/src/grin/sync/syncer.rs
  src/bin/tui/status.rs
  store/src/pmmr.rs
  store/tests/pmmr.rs
Labels: P3: Fix if time, enhancement

#3118 Replace MimbleWimble by Mimblewimble
  CONTRIBUTING.md
  Cargo.toml
  README.md
  api/Cargo.toml
  chain/Cargo.toml
  config/Cargo.toml
  core/Cargo.toml
  core/src/core/block.rs
  core/src/lib.rs
  doc/chain/chain_sync.md
  doc/chain/chain_sync_KR.md
  doc/contract_ideas.md
  doc/grin4bitcoiners.md
  doc/grin4bitcoiners_KR.md
  doc/grin4bitcoiners_ZH-CN.md
  doc/intro.md
  doc/intro_DE.md
  doc/intro_ES.md
  doc/intro_KR.md
  doc/intro_NL.md
  doc/intro_PT-BR.md
  doc/intro_SE.md
  doc/intro_ZH-CN.md
  doc/merkle.md
  doc/merkle_KR.md
  doc/pruning.md
  doc/pruning_KR.md
  doc/switch_commitment.md
  doc/toc.md
  keychain/Cargo.toml
  p2p/Cargo.toml
  pool/Cargo.toml
  servers/Cargo.toml
  src/bin/grin.yml
  store/Cargo.toml
  util/Cargo.toml
Labels: task

#3133 mismatch between the test dir used and the test dir cleaned up...
  chain/tests/test_coinbase_maturity.rs
Labels: bug

#3139 use saturating_sub() to avoid a negative value causing an overflow panic (tui logs)
  src/bin/tui/logs.rs
Labels: bug

#3108 Enable faster sync
  Cargo.lock
  api/src/types.rs
  chain/Cargo.toml
  chain/src/chain.rs
  chain/src/txhashset.rs
  chain/src/txhashset/bitmap_accumulator.rs
  chain/src/txhashset/txhashset.rs
  chain/src/types.rs
  chain/tests/bitmap_accumulator.rs
  core/src/core/pmmr.rs
  core/src/core/pmmr/backend.rs
  core/src/core/pmmr/pmmr.rs
  core/src/core/pmmr/readonly_pmmr.rs
  core/src/core/pmmr/vec_backend.rs
  core/tests/block.rs
  core/tests/common.rs
  core/tests/merkle_proof.rs
  core/tests/pmmr.rs
  core/tests/vec_backend.rs
  store/Cargo.toml
  store/src/pmmr.rs
  store/tests/pmmr.rs
Labels: enhancement, must-have

#3142 Call zip_read() from within the txhashet lock for a consistent view on the files
  chain/src/chain.rs
  chain/src/txhashset/txhashset.rs
Labels: enhancement

#3148 explicit header version based on height rather than "incrementing" the version
  core/src/core/block.rs
Labels: enhancement

#3150 cleanup HeaderVersion, "newtype" no need for constructor
  core/src/consensus.rs
  core/src/core/block.rs
  core/src/global.rs
  core/tests/consensus.rs
Labels: enhancement

#3154 our TCP listener is nonblocking so we *must* set the accepted stream to blocking explicitly
  p2p/src/serv.rs
Labels: bug, fixed
