Repository mimblewimble/grin, pull requests merged in 2019-12, with the labels that each got.

#3149 cleanup HeaderVersion::default()
  core/src/core/block.rs
  core/tests/block.rs
Labels: enhancement

#3156 Deadlock possible in check_orphans() called from txhashset_write()
  chain/src/chain.rs
Labels: bug, fixed

#3147 height (header version) specific output PMMR root rules
  api/src/handlers/transactions_api.rs
  api/src/types.rs
  chain/src/chain.rs
  chain/src/pipe.rs
  chain/src/types.rs
  core/src/consensus.rs
  core/src/core/block.rs
Labels: consensus breaking

#3157 pass stopped into consume so we can halt txhashset mid download
  p2p/src/conn.rs
  p2p/src/protocol.rs
Labels: enhancement

#3094 Node API v2
  .gitignore
  Cargo.lock
  api/Cargo.toml
  api/src/auth.rs
  api/src/foreign.rs
  api/src/foreign_rpc.rs
  api/src/handlers.rs
  api/src/handlers/blocks_api.rs
  api/src/handlers/chain_api.rs
  api/src/handlers/peers_api.rs
  api/src/handlers/pool_api.rs
  api/src/handlers/server_api.rs
  api/src/handlers/transactions_api.rs
  api/src/handlers/utils.rs
  api/src/handlers/version_api.rs
  api/src/lib.rs
  api/src/owner.rs
  api/src/owner_rpc.rs
  api/src/rest.rs
  api/src/router.rs
  api/src/types.rs
  api/src/web.rs
  chain/src/chain.rs
  chain/src/txhashset/txhashset.rs
  chain/src/txhashset/utxo_view.rs
  config/src/comments.rs
  config/src/config.rs
  pool/src/types.rs
  servers/src/common/types.rs
  servers/src/grin/server.rs
Labels: P2: Important, enhancement

#3164 drop msg if sync_sender buffer is full (do not close peer connection)
  p2p/src/conn.rs
  p2p/src/types.rs
Labels: enhancement
