Repository mimblewimble/grin, pull requests merged in 2019-08, with the labels that each got.

#2986 cleanup and simplify how we generate the genesis block in user_testing
  core/src/genesis.rs
  core/src/global.rs
  servers/src/grin/server.rs
Labels: bug

#2984 TxHashSet Download Improvement
  chain/src/chain.rs
  p2p/src/peer.rs
  p2p/src/peers.rs
  p2p/src/protocol.rs
  servers/src/common/adapters.rs
Labels: enhancement

#2859 fee and lock_height maintained in kernel features variants
  api/src/types.rs
  core/src/core/block.rs
  core/src/core/hash.rs
  core/src/core/transaction.rs
  core/src/genesis.rs
  core/src/libtx/aggsig.rs
  core/src/libtx/reward.rs
  core/src/ser.rs
  core/tests/block.rs
  core/tests/core.rs
Labels: enhancement

#2993 improve checking for p2p connection limits (revised)
  config/src/comments.rs
  p2p/src/peers.rs
  p2p/src/serv.rs
  p2p/src/types.rs
  servers/src/grin/seed.rs
  servers/src/grin/sync/syncer.rs
Labels: enhancement

#2996 simplify broadcast - send to all connected peers
  p2p/src/peers.rs
Labels: enhancement

#2997 cleanup deprecation warnings about missing dyn with trait objects
  chain/src/chain.rs
  core/src/core/block.rs
  core/src/core/pmmr/backend.rs
  core/src/core/pmmr/rewindable_pmmr.rs
  p2p/src/peer.rs
  p2p/src/peers.rs
  p2p/src/serv.rs
  p2p/src/types.rs
  servers/src/common/adapters.rs
  servers/src/common/hooks.rs
  servers/src/grin/dandelion_monitor.rs
  store/src/pmmr.rs
Labels: task

#3005 Fix invalid root
  chain/src/txhashset/txhashset.rs
  chain/tests/mine_simple_chain.rs
Labels: bug, fixed

#3007 verify the ignored fee is still 0
  core/src/core/transaction.rs
Labels: bug, fixed

#2903 store both mmr index and block height into database for output
  api/src/handlers/transactions_api.rs
  api/src/handlers/utils.rs
  api/src/types.rs
  chain/src/chain.rs
  chain/src/store.rs
  chain/src/txhashset/txhashset.rs
  chain/src/types.rs
  servers/src/grin/server.rs
  store/src/lmdb.rs
Labels: enhancement
