Repository mimblewimble/grin, pull requests merged in 2019-10, with the labels that each got.

#3075 bump version to v2.1.0-beta.3
  Cargo.lock
  Cargo.toml
  api/Cargo.toml
  chain/Cargo.toml
  config/Cargo.toml
  core/Cargo.toml
  keychain/Cargo.toml
  p2p/Cargo.toml
  pool/Cargo.toml
  servers/Cargo.toml
  store/Cargo.toml
  util/Cargo.toml
Labels: task

#3086 More robust peer banning
  api/src/handlers/peers_api.rs
  p2p/src/peers.rs
  p2p/src/types.rs
  servers/src/grin/seed.rs
  servers/src/grin/sync/header_sync.rs
Labels: enhancement

#3068 quick check for block_exists in adapters
  servers/src/common/adapters.rs
Labels: enhancement

#3067 Use sender thread consistently to send msgs to a peer
  p2p/src/conn.rs
  p2p/src/handshake.rs
  p2p/src/msg.rs
  p2p/src/peer.rs
  p2p/src/protocol.rs
Labels: enhancement

#3078 chore: pre-commit hook - format all staged files, re-add then commit
  .hooks/pre-commit
Labels: enhancement

#3088 use remove_range_closed() for clarity
  store/src/leaf_set.rs
Labels: enhancement

#3089 node incorrectly suppresses header broadcast for full blocks (after failing to hydrate a compact block)
  Cargo.lock
  p2p/Cargo.toml
  p2p/src/peer.rs
  p2p/src/peers.rs
  p2p/src/protocol.rs
  p2p/src/serv.rs
  p2p/src/types.rs
  servers/src/common/adapters.rs
  servers/src/grin/sync/body_sync.rs
Labels: bug

#3090 skip hydrate if missing kernels, just request full block
  servers/src/common/adapters.rs
Labels: enhancement

#3097 Remove usage of try! macro, use ? instead
  core/src/macros.rs
  core/tests/vec_backend.rs
  keychain/src/extkey_bip32.rs
  keychain/src/mnemonic.rs
  keychain/src/types.rs
Labels: task

#3023 Verify headers and blocks only when needed
  chain/src/pipe.rs
  core/fuzz/Cargo.lock
  core/fuzz/fuzz_targets/block_read_v1.rs
  core/fuzz/fuzz_targets/block_read_v2.rs
  core/fuzz/fuzz_targets/compact_block_read_v1.rs
  core/fuzz/fuzz_targets/compact_block_read_v2.rs
  core/src/core/block.rs
  core/src/core/compact_block.rs
  core/src/pow/cuckatoo.rs
  core/src/pow/types.rs
  p2p/src/protocol.rs
Labels: enhancement

#3045 Read header_head and sync_head from header MMRs directly
  chain/src/chain.rs
  chain/src/pipe.rs
  chain/src/store.rs
  chain/src/txhashset/txhashset.rs
  pool/tests/common.rs
  servers/src/grin/sync/header_sync.rs
Labels: enhancement
