Repository mimblewimble/grin, pull requests merged in 2019-03, with the labels that each got.

#2633 Display the current download rate rather than the average when syncing the chain
  servers/src/common/adapters.rs
  servers/src/common/types.rs
  servers/src/grin/sync/state_sync.rs
  src/bin/tui/status.rs
Labels: enhancement

#2601 add a new configure item for log_max_files
  config/src/comments.rs
  util/src/logger.rs
  util/src/types.rs
Labels: enhancement

#2680 Set Content-Type in API client
  api/src/client.rs
Labels: task

#2675 [1.1.0] Bring fuzz test back
  core/fuzz/Cargo.lock
  core/fuzz/README.md
  core/fuzz/fuzz_targets/block_read.rs
  core/fuzz/fuzz_targets/compact_block_read.rs
  core/fuzz/fuzz_targets/transaction_read.rs
  core/fuzz/src/main.rs
Labels: task

#2679 Reduce number of unwraps in chain crate
  chain/src/chain.rs
  chain/src/pipe.rs
  chain/src/store.rs
  chain/src/txhashset/txhashset.rs
  chain/tests/data_file_integrity.rs
  chain/tests/mine_simple_chain.rs
  chain/tests/test_coinbase_maturity.rs
  servers/src/grin/server.rs
  servers/src/grin/sync/body_sync.rs
  servers/src/grin/sync/syncer.rs
  servers/src/mining/mine_block.rs
  wallet/src/test_framework/mod.rs
Labels: task

#2681 Reduce number of unwwaps in api crate
  api/src/auth.rs
  api/src/client.rs
  api/src/handlers.rs
  api/src/handlers/blocks_api.rs
  api/src/handlers/chain_api.rs
  api/src/handlers/peers_api.rs
  api/src/handlers/pool_api.rs
  api/src/handlers/server_api.rs
  api/src/handlers/transactions_api.rs
  api/src/handlers/utils.rs
  api/src/lib.rs
  api/src/rest.rs
  api/src/types.rs
  api/src/web.rs
  api/tests/rest.rs
  wallet/src/controller.rs
  wallet/src/test_framework/mod.rs
Labels: task

#2628 Dandelion++ Rewrite
  config/src/comments.rs
  p2p/src/peer.rs
  p2p/src/peers.rs
  pool/src/lib.rs
  pool/src/pool.rs
  pool/src/transaction_pool.rs
  pool/src/types.rs
  servers/src/common/adapters.rs
  servers/src/common/types.rs
  servers/src/grin/dandelion_monitor.rs
  servers/src/grin/seed.rs
  servers/src/grin/server.rs
Labels: enhancement

#2695 Disable hooks during sync
  servers/src/common/adapters.rs
Labels: enhancement

#2686 catch the panic to avoid peer thread quit early
  util/src/zip.rs
Labels: bug

#2683 Show response code in API client error message
  api/src/client.rs
Labels: task

#2685 use sandbox folder for txhashset validation on state sync
  chain/src/chain.rs
  chain/src/txhashset/txhashset.rs
  chain/tests/test_txhashset.rs
  servers/src/common/adapters.rs
Labels: bug

#2713 Attempt to fix broken TUI locale
  Cargo.lock
  Cargo.toml
Labels: bug

#2707 Reduce number of unwarps in servers crate
  pool/src/types.rs
  servers/src/common/types.rs
  servers/src/grin/dandelion_monitor.rs
  servers/src/grin/seed.rs
  servers/src/grin/server.rs
  servers/src/grin/sync/body_sync.rs
  servers/src/grin/sync/header_sync.rs
  servers/src/grin/sync/state_sync.rs
  servers/src/grin/sync/syncer.rs
  servers/src/mining/mine_block.rs
  servers/tests/simulnet.rs
Labels: task
