Repository mimblewimble/grin, pull requests merged in 2020-06, with the labels that each got.

#3334 HardFork3
  core/src/consensus.rs
  core/src/global.rs
  core/src/pow.rs
  core/src/pow/cuckarooz.rs
  core/tests/consensus_floonet.rs
  core/tests/consensus_mainnet.rs
Labels: consensus breaking, must-have

#3338 Cargo Update
  Cargo.lock
  Cargo.toml
  api/Cargo.toml
  chain/Cargo.toml
  config/Cargo.toml
  core/Cargo.toml
  keychain/Cargo.toml
  p2p/Cargo.toml
  pool/Cargo.toml
  servers/Cargo.toml
  servers/src/common/hooks.rs
  src/bin/tui/ui.rs
  src/build/build.rs
  store/Cargo.toml
  util/Cargo.toml
Labels: enhancement

#3350 Cargo update
  Cargo.lock
Labels: task

#3347 Remove wallet from CLI
  src/bin/grin.rs
  src/bin/grin.yml
Labels: task

#3351 bump version to 4.0.0-beta.2
  Cargo.lock
  Cargo.toml
  api/Cargo.toml
  chain/Cargo.toml
  config/Cargo.toml
  core/Cargo.toml
  keychain/Cargo.toml
  p2p/Cargo.toml
  pool/Cargo.toml
  servers/Cargo.toml
  store/Cargo.toml
  util/Cargo.toml
Labels: task

#3355 cleanup old unused code
  chain/src/chain.rs
  chain/src/txhashset/rewindable_kernel_view.rs
  core/src/core/pmmr/backend.rs
  core/src/core/pmmr/vec_backend.rs
  p2p/src/peer.rs
  p2p/src/peers.rs
  p2p/src/serv.rs
  p2p/src/types.rs
  servers/src/common/adapters.rs
  store/src/pmmr.rs
  store/src/types.rs
Labels: task

#3362 make sure header PMMR is init correctly based on header_head from db
  chain/src/chain.rs
  chain/src/pipe.rs
  chain/src/txhashset/txhashset.rs
Labels: enhancement
