Repository mimblewimble/grin, pull requests merged in 2020-07, with the labels that each got.

#3374 bump master to 4.0.1-alpha.1 to differentiate from 4.0.0 official tagged build
  Cargo.lock
  Cargo.toml
  api/Cargo.toml
  chain/Cargo.toml
  config/Cargo.toml
  core/Cargo.toml
  keychain/Cargo.toml
  p2p/Cargo.toml
  pool/Cargo.toml
  servers/Cargo.toml
  store/Cargo.toml
  util/Cargo.toml
Labels: task

#3376 log reorg (and fork) depth correctly
  chain/src/chain.rs
  chain/src/pipe.rs
  chain/src/types.rs
  chain/tests/mine_simple_chain.rs
  servers/src/common/adapters.rs
  servers/src/common/hooks.rs
Labels: enhancement

#3387 more robust handling of min_height and max_height in get_kernel_height()
  chain/src/chain.rs
  chain/tests/test_get_kernel_height.rs
Labels: bug, fixed

#3400 Include height for spent outputs in get_outputs api
  api/src/types.rs
  chain/src/chain.rs
Labels: bug, fixed

#3403 Update current/4.0.x to alpha.1
  Cargo.lock
  Cargo.toml
  api/Cargo.toml
  chain/Cargo.toml
  config/Cargo.toml
  core/Cargo.toml
  keychain/Cargo.toml
  p2p/Cargo.toml
  pool/Cargo.toml
  servers/Cargo.toml
  store/Cargo.toml
  util/Cargo.toml
Labels: task

#3404 pass slices around and not refs to vecs
  chain/src/store.rs
  chain/tests/chain_test_helper.rs
  chain/tests/mine_nrd_kernel.rs
  chain/tests/mine_simple_chain.rs
  chain/tests/nrd_validation_rules.rs
  chain/tests/test_coinbase_maturity.rs
  core/src/core/block.rs
  core/src/core/compact_block.rs
  core/src/core/transaction.rs
  core/src/libtx/build.rs
  core/tests/block.rs
  core/tests/common.rs
  core/tests/consensus_mainnet.rs
  core/tests/core.rs
  pool/src/pool.rs
  pool/src/transaction_pool.rs
  pool/tests/block_building.rs
  pool/tests/block_max_weight.rs
  pool/tests/block_reconciliation.rs
  pool/tests/coinbase_maturity.rs
  pool/tests/common.rs
  pool/tests/nrd_kernel_relative_height.rs
  pool/tests/nrd_kernels_disabled.rs
  pool/tests/nrd_kernels_enabled.rs
  pool/tests/transaction_pool.rs
  servers/src/common/adapters.rs
  servers/src/grin/dandelion_monitor.rs
  servers/src/mining/mine_block.rs
  src/bin/tui/table.rs
Labels: enhancement

#3409 refactor apply_inputs and support converting block for v2 compatibility
  chain/src/chain.rs
  chain/src/pipe.rs
  chain/src/store.rs
  chain/src/txhashset/txhashset.rs
  chain/src/txhashset/utxo_view.rs
  chain/tests/test_block_known.rs
  core/src/core/transaction.rs
Labels: enhancement
