Repository mimblewimble/grin, pull requests merged in 2020-01, with the labels that each got.

#3175 Fix compiler warning 'unnecessary parentheses around type'
  chain/src/txhashset/txhashset.rs
  core/src/core/committed.rs
  store/src/pmmr.rs
Labels: task

#3184 TUI peer sort order
  src/bin/tui/peers.rs
Labels: enhancement

#3185 Remove unused crates
  Cargo.lock
  chain/Cargo.toml
  core/Cargo.toml
  keychain/Cargo.toml
  p2p/Cargo.toml
  pool/Cargo.toml
  servers/Cargo.toml
  store/Cargo.toml
Labels: task

#3195 Remove old website for grin.mw
  CONTRIBUTING.md
  SECURITY.md
  core/src/pow/cuckarood.rs
  core/src/pow/cuckaroom.rs
Labels: task

#3200 Bug fix for highest_index in output API.
  chain/src/txhashset/txhashset.rs
Labels: bug

#3186 Fix return code in peers API
  api/src/handlers/peers_api.rs
Labels: bug

#3178 Build block header from pre pow data and proof
  core/src/core/block.rs
  core/tests/block.rs
Labels: enhancement

#3207 cleanup unused hash_with impl
  core/src/core/hash.rs
  core/src/core/transaction.rs
Labels: enhancement

#3176 Refactor to pass batch around explicitly
  chain/src/chain.rs
  chain/src/pipe.rs
  chain/src/txhashset/rewindable_kernel_view.rs
  chain/src/txhashset/txhashset.rs
  chain/src/txhashset/utxo_view.rs
Labels: enhancement

#3211 Tests: remove unused crate
  core/tests/block.rs
Labels: task

#3205 Some simple Option / Result / iterator pattern simplifications
  api/src/handlers/chain_api.rs
  api/src/types.rs
  api/src/web.rs
  core/src/libtx/proof.rs
  keychain/src/extkey_bip32.rs
  pool/src/pool.rs
  src/bin/tui/mining.rs
  store/src/leaf_set.rs
  store/src/types.rs
  util/src/file.rs
Labels: enhancement

#3132 Remove Writeable impl for [u8; 4]
  core/src/ser.rs
Labels: enhancement

#3215 Replace Gitter by Keybase in README.MD
  README.md
Labels: task
