Repository mimblewimble/grin, pull requests merged in 2020-02, with the labels that each got.

#3217 Optimization: Pass SwitchCommitment by value instead of reference
  core/src/core/transaction.rs
  core/src/libtx/aggsig.rs
  core/src/libtx/build.rs
  core/src/libtx/proof.rs
  core/src/libtx/reward.rs
  core/tests/transaction.rs
  core/tests/verifier_cache.rs
  keychain/src/keychain.rs
  keychain/src/types.rs
  keychain/src/view_key.rs
Labels: enhancement, task

#3220 CI: Remove Rust installation for macOS
  .ci/install.yml
Labels: task

#3216 Less cloning and pattern simplifications
  chain/src/chain.rs
  chain/src/pipe.rs
  chain/src/store.rs
  chain/src/txhashset/bitmap_accumulator.rs
  chain/src/txhashset/txhashset.rs
  chain/src/txhashset/utxo_view.rs
  core/src/consensus.rs
  core/src/core/id.rs
  core/src/global.rs
  core/src/libtx/build.rs
  core/src/libtx/proof.rs
  core/src/pow/cuckaroo.rs
  core/src/pow/cuckarood.rs
  core/src/pow/cuckaroom.rs
  core/src/pow/cuckatoo.rs
  core/src/pow/siphash.rs
  core/src/pow/types.rs
  core/src/ser.rs
  core/tests/block.rs
  core/tests/common.rs
  core/tests/consensus_automated.rs
  core/tests/consensus_mainnet.rs
  core/tests/core.rs
  core/tests/pmmr.rs
  core/tests/verifier_cache.rs
  keychain/src/extkey_bip32.rs
  keychain/src/keychain.rs
  keychain/src/mnemonic.rs
  keychain/src/types.rs
  keychain/src/view_key.rs
  util/src/hex.rs
  util/src/rate_counter.rs
  util/src/zip.rs
  util/tests/file.rs
Labels: task

#3223 Less cloning and additional pattern simplifications
  api/src/auth.rs
  api/src/client.rs
  api/src/handlers.rs
  api/src/handlers/blocks_api.rs
  api/src/handlers/chain_api.rs
  api/src/handlers/pool_api.rs
  api/src/handlers/server_api.rs
  api/src/handlers/utils.rs
  api/src/handlers/version_api.rs
  api/src/rest.rs
  api/src/router.rs
  api/src/types.rs
  api/src/web.rs
  chain/src/chain.rs
  chain/src/pipe.rs
  chain/src/store.rs
  chain/src/txhashset/txhashset.rs
  chain/src/txhashset/utxo_view.rs
  chain/src/types.rs
  core/src/core/transaction.rs
  core/src/libtx/aggsig.rs
  core/src/libtx/proof.rs
  core/src/libtx/secp_ser.rs
  core/src/pow/cuckaroo.rs
  core/src/pow/cuckarood.rs
  core/src/pow/cuckaroom.rs
  core/src/pow/cuckatoo.rs
  core/src/ser.rs
  keychain/src/base58.rs
  keychain/src/extkey_bip32.rs
  keychain/src/types.rs
  p2p/src/conn.rs
  p2p/src/msg.rs
  p2p/src/peers.rs
  p2p/src/store.rs
  p2p/src/types.rs
  pool/src/pool.rs
  pool/src/transaction_pool.rs
  store/src/lmdb.rs
  store/src/pmmr.rs
  store/src/types.rs
  util/src/file.rs
  util/src/logger.rs
Labels: task

#3221 Attempt to read ipv4-mapped ipv6 to ipv4 if possible
  p2p/src/types.rs
Labels: enhancement

#3229 Account for the utxo rewind when attempting to fix a bad chain init
  chain/src/chain.rs
Labels: enhancement

#3227 Cleanup output pos idx
  chain/src/chain.rs
  chain/src/store.rs
  chain/src/txhashset/txhashset.rs
Labels: enhancement

#3214 Update hyper/tokio/futures dependencies
  Cargo.lock
  api/Cargo.toml
  api/src/auth.rs
  api/src/client.rs
  api/src/handlers.rs
  api/src/handlers/pool_api.rs
  api/src/rest.rs
  api/src/router.rs
  api/src/web.rs
  rustfmt.toml
  servers/Cargo.toml
  servers/src/common/hooks.rs
  servers/src/mining/stratumserver.rs
Labels: enhancement

#3233 Update croaring
  .ci/install.yml
  Cargo.lock
  chain/Cargo.toml
  core/Cargo.toml
  core/fuzz/Cargo.lock
  store/Cargo.toml
  store/src/leaf_set.rs
  store/src/prune_list.rs
Labels: task

#3236 Block input bitmap rework
  api/src/handlers/utils.rs
  chain/src/chain.rs
  chain/src/pipe.rs
  chain/src/store.rs
  chain/src/txhashset/txhashset.rs
  chain/src/types.rs
  chain/tests/mine_simple_chain.rs
Labels: enhancement

#3241 handle mpsc channel disconnect from peer_write thread
  p2p/src/conn.rs
Labels: bug

#3243 ignore error from set_read_timeout
  p2p/src/conn.rs
Labels: bug

#3249 explicit read_timeout and write_timeout during hand/shake
  p2p/src/handshake.rs
Labels: bug

#3244 bump version to 3.1.0-beta.2
  Cargo.lock
  Cargo.toml
  api/Cargo.toml
  chain/Cargo.toml
  config/Cargo.toml
  core/Cargo.toml
  core/fuzz/Cargo.lock
  keychain/Cargo.toml
  p2p/Cargo.toml
  pool/Cargo.toml
  servers/Cargo.toml
  store/Cargo.toml
  util/Cargo.toml
Labels: task

#3252 bump to 3.1.0-beta.3
  Cargo.lock
  Cargo.toml
  api/Cargo.toml
  chain/Cargo.toml
  config/Cargo.toml
  core/Cargo.toml
  core/fuzz/Cargo.lock
  keychain/Cargo.toml
  p2p/Cargo.toml
  pool/Cargo.toml
  servers/Cargo.toml
  store/Cargo.toml
  util/Cargo.toml
Labels: task
