Repository mimblewimble/grin, pull requests merged in 2020-05, with the labels that each got.

#3324 Partial Cargo.lock Update
  Cargo.lock
  api/Cargo.toml
  servers/Cargo.toml
Labels: enhancement, fixed

#3319 Refactor bucket_transactions() and evict_transaction()
  pool/src/pool.rs
  pool/src/transaction_pool.rs
Labels: enhancement

#3323 Fix miminum share difficulty in Stratum Server
  servers/src/mining/stratumserver.rs
Labels: fixed

#3315 Remove unnecessary newline in Stratum message
  servers/src/mining/stratumserver.rs
Labels: fixed

#3331 Remove compiler warniing
  servers/src/mining/stratumserver.rs
Labels: task

#3327 thread local chain type vs global chain type
  chain/tests/chain_test_helper.rs
  chain/tests/mine_simple_chain.rs
  chain/tests/test_coinbase_maturity.rs
  chain/tests/test_txhashset.rs
  core/src/consensus.rs
  core/src/genesis.rs
  core/src/global.rs
  core/src/libtx/build.rs
  core/src/pow.rs
  core/src/pow/cuckaroo.rs
  core/src/pow/cuckarood.rs
  core/src/pow/cuckaroom.rs
  core/src/pow/cuckatoo.rs
  core/src/pow/lean.rs
  core/src/pow/types.rs
  core/tests/block.rs
  core/tests/consensus_automated.rs
  core/tests/consensus_floonet.rs
  core/tests/consensus_mainnet.rs
  core/tests/core.rs
  etc/gen_gen/src/bin/gen_gen.rs
  p2p/src/msg.rs
  p2p/tests/peer_handshake.rs
  pool/src/types.rs
  pool/tests/block_building.rs
  pool/tests/block_max_weight.rs
  pool/tests/block_reconciliation.rs
  pool/tests/coinbase_maturity.rs
  pool/tests/transaction_pool.rs
  src/bin/cmd/server.rs
  src/bin/grin.rs
  store/tests/lmdb.rs
  util/src/lib.rs
Labels: enhancement

#3303 Enable NRD kernel support (noop) feature flagged
  api/src/types.rs
  chain/tests/chain_test_helper.rs
  chain/tests/mine_nrd_kernel.rs
  chain/tests/mine_simple_chain.rs
  core/src/consensus.rs
  core/src/core/block.rs
  core/src/core/transaction.rs
  core/src/global.rs
  core/src/libtx/aggsig.rs
  core/src/ser.rs
  core/tests/block.rs
  pool/src/transaction_pool.rs
  pool/src/types.rs
  pool/tests/common.rs
  pool/tests/nrd_kernels.rs
  src/bin/grin.rs
Labels: consensus breaking, enhancement, must-have

#3298 check_known now takes total_difficulty into consideration
  chain/src/pipe.rs
  chain/tests/test_block_known.rs
Labels: enhancement

#3336 display chain type on tui title bar
  src/bin/tui/ui.rs
Labels: enhancement
