Repository mimblewimble/grin, pull requests merged in 2020-08, with the labels that each got.

#3411 use AsRef in cut_through for flexibility
  core/src/core/transaction.rs
Labels: enhancement

#3412 Tx conversion for v2 compatibility
  chain/src/chain.rs
  core/src/core/transaction.rs
  pool/src/pool.rs
  pool/src/transaction_pool.rs
  pool/src/types.rs
  pool/tests/common.rs
  pool/tests/transaction_pool.rs
  servers/src/common/adapters.rs
  servers/src/grin/dandelion_monitor.rs
Labels: enhancement

#3418 orphan check needs to handle fast sync "edge case"
  chain/src/chain.rs
  chain/src/pipe.rs
Labels: bug, fixed

#3426 Update dockerfiles with rust 1.45 and Debian Buster
  etc/Dockerfile
  etc/Dockerfile.floonet
Labels: enhancement

#3397 use sync pmmr for building locator
  chain/src/chain.rs
  servers/src/grin/sync/header_sync.rs
Labels: enhancement

#3381 Fix #3380 Broken API Links
  api/src/foreign_rpc.rs
  api/src/owner_rpc.rs
Labels: task

#3424 verify_cut_through and test coverage
  chain/src/chain.rs
  chain/src/pipe.rs
  chain/src/txhashset/txhashset.rs
  chain/tests/process_block_cut_through.rs
  core/src/core/transaction.rs
  core/tests/block.rs
  core/tests/transaction.rs
Labels: bug, fixed

#3379 further tweaks to block_accepted logs for clarity
  chain/src/chain.rs
  chain/src/types.rs
  chain/tests/mine_simple_chain.rs
  servers/src/common/hooks.rs
Labels: enhancement
